apiVersion: v1
kind: Service
metadata:
  name: sharerecipe-profile-db
  namespace: sharerecipe
  labels:
    app: sharerecipe-profile-db
    service: sharerecipe-profile-db
spec:
  selector:
    app: sharerecipe-profile-db-pod
  ports:
    - protocol: TCP
      name: tcp-psql
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharerecipe-profile-db
  namespace: sharerecipe
spec:
  selector:
    matchLabels:
      app: sharerecipe-profile-db-pod
      version: latest
  template:
    metadata:
      labels:
        app: sharerecipe-profile-db-pod
        version: latest
    spec:
      containers:
        - name: sharerecipe-profile-db-container
          image: postgres:13.2
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              memory: 200Mi
              cpu: 300m
          ports:
            - containerPort: 5432
          #envFrom:
          #  - secretRef:
          #      name: sharerecipe-profile-db-secret
          volumeMounts:
            - name: sharerecipe-profile-db-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: sharerecipe-profile-db-volume
          persistentVolumeClaim:
            claimName: sharerecipe-profile-db-volume-claim