apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-db-volume-claim
  namespace: keycloak
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-db-volume
  namespace: keycloak
  labels:
    type: local
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/keycloak-db/
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: keycloak-db-volume-claim
    namespace: keycloak
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube