apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sharerecipe-profile-db-volume-claim
  namespace: sharerecipe
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 4Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sharerecipe-profile-db-volume
  namespace: sharerecipe
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
parameters:
  storageaccounttype: Premium_LRS
  kind: managed
