apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: share-service
spec:
  selector:
    app: auth-share
  type: LoadBalancer
  ports:
    - name: share-port
      port: 8080
      targetPort: 80
